modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="show_fps"
version="1.0.0"
displayName="Show FPS"
credits="FinnT730, and @Su5eD for the PR"
displayURL=""
authors="FinnT730"

[[dependencies.show_fps]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




